CREATE DATABASE BANGLORE;
SHOW DATABASES;
USE BANGLORE;
SELECT DATABASE();
CREATE TABLE METRO_DETAILS(
NAME VARCHAR(20),
PLACE VARCHAR(20),
HEAD_QUATERS VARCHAR(45),
WEBSITE VARCHAR(20),
TRAIN_LENGTH VARCHAR(50),
ELECTRIFICATION VARCHAR(20),
TOP_SPEED VARCHAR(30),
NO_OF_TRACKS INT,
HEADWAY VARCHAR(20),
METROCARDNUMBER LONG);
SELECT * FROM METRO_DETAILS;
INSERT INTO METRO_DETAILS VALUES('NAMMO METRO','BANGLORE','BMTC CENTRAL OFFICE','bmrc.co.in','6 COACHES','750 V DC','80 KM',2,'3-5MIN',120225677,'END STATION');
ALTER TABLE METRO_DETAILS RENAME METRO;
ALTER TABLE METRO_DETAILS ADD COLUMN TERMINATED_PLACE VARCHAR(40);
ALTER TABLE METRO_DETAILS DROP COLUMN TRAIN_LENGTH;
ALTER TABLE METRO_DETAILS CHANGE NAME METROCARDNUMBER INT;

CREATE TABLE RESTOURANT_DETAILS(
NAME VARCHAR(30),
PLACE VARCHAR(30),
ONE_DAY_PRICE INT,
TOTAL_RESTOURANT INT,
WHICH_TYPE VARCHAR(30),
RATINGS FLOAT,
HIGHLIGHTS VARCHAR(40),
OPENING_TIME VARCHAR(30),
CLOSING_TIME VARCHAR(30),
PHONENUMBER INT);
SELECT * FROM RESTOURANT_DETAILS;
ALTER TABLE RESTOURANT_DETAILS RENAME RESTOURANT_INFO;
INSERT INTO RESTOURANT_DETAILS VALUES('FATTY BAO','BANGLORE',1000,100,'NONVEG',4.9,'RESEVING TABLES','11AM','8PM',9765478889);
ALTER TABLE RESTOURANT_DETAILS MODIFY COLUMN PHONENUMBER LONG;
ALTER TABLE RESTOURANT_DETAILS RENAME COLUMN PLACE TO PLACE_INFO;
ALTER TABLE RESTOURANT_DETAILS ADD COLUMN HONAR_NAME VARCHAR(30);
ALTER TABLE RESTOURANT_DETAILS DROP COLUMN WHICH_TYPE;
ALTER TABLE RESTOURANT_DETAILS CHANGE NAME PHONENUMBER INT;

CREATE TABLE MALLS_INFO(
NAME VARCHAR(30),
TOTAL_MALLS INT,
PLACE VARCHAR(30),
HOW_MANY_SHOPS INT,
OPENING VARCHAR(20),
CLOSING VARCHAR(20),
CONTACT_NUMBER LONG,
HOW_MANY_MALLS INT,
TOTAL_GAMES INT,
RATINGS FLOAT);
SELECT * FROM  MALLS_INFO;
INSERT INTO  MALLS_INFO VALUES('ORIAN MALL',25,'BANGLORE',20,'10PM',9876549876,30,15,4.5,1);
ALTER TABLE  MALLS_INFO RENAME MALLS_DETAILS;
ALTER TABLE MALLS_INFO ADD COLUMN CINEMA_HALL VARCHAR(30);
ALTER TABLE MALLS_INFO RENAME COLUMN TOTAL_MALLS TO NUMBER_OF_MALLS;
ALTER TABLE  MALLS_INFO DROP COLUMN OPENING;
ALTER TABLE  MALLS_INFO MODIFY RATINGS DOUBLE;
ALTER TABLE  MALLS_INFO MODIFY  HOW_MANY_MALLS LONG;

CREATE TABLE RESORTS_DETAILS(
NAME VARCHAR(30),
NO_OF_RESORTS INT,
OPENING VARCHAR(30),
CLOSING VARCHAR(20),
PLACE VARCHAR(30),
AMMOUNT INT,
SWIMMING_POOL INT,
INDOOR_GAMES INT,
OUTDOOR_GAMES INT,
RATINGS DOUBLE);
SELECT * FROM RESORTS_DETAILS;
ALTER TABLE RESORTS_DETAILS RENAME RESORTS_INFO;
ALTER TABLE RESORTS_INFO ADD COLUMN ROPE_ACTIVITIES VARCHAR(20);
ALTER TABLE RESORTS_INFO RENAME COLUMN NO_OF_RESORTS TO TOTAL_RESORTS;
INSERT INTO RESORTS_DETAILS VALUES('HOMALE RESORTS',25,'10AM','9PM',13000,1,5,15,4.2,'10 TYPE');
ALTER TABLE RESORTS_INFO DROP COLUMN PLACE;
ALTER TABLE RESORTS_INFO MODIFY RATINGS FLOAT;

CREATE TABLE SHOWROOMS_DETAILS(
NAME VARCHAR(20),
VEHICLE VARCHAR(30),
OPENING VARCHAR(30),
CLOSING VARCHAR(30),
TOTAL_SHOWROOMS INT,
PLACE VARCHAR(30),
NEW_MODEL VARCHAR(30),
TOTAL_MODELS INT,
AMOUNT VARCHAR(30),
REVIEW FLOAT);
ALTER TABLE SHOWROOMS_DETAILS RENAME SHOWROOMS_INFO;
ALTER TABLE SHOWROOMS_INFO ADD COLUMN HONAR_NAME VARCHAR(30);
ALTER TABLE SHOWROOMS_INFO RENAME COLUMN VEHICLE TO VEHICLE_INFO; 
ALTER TABLE  SHOWROOMS_INFO DROP COLUMN TOTAL_SHOWROOMS;
ALTER TABLE SHOWROOMS_INFO MODIFY REVIEW DOUBLE;
INSERT INTO SHOWROOMS_INFO VALUES('TATA SHOWROOMS','CAR','9AM','10PM','BANGLORE','NEXAAN',10,'15LAKHS',4.8,'KIRAN JOSHI');
SELECT * FROM SHOWROOMS_INFO;
DROP TABLE MALLS_DETAILS;
DROP TABLE MALLS_INFO;








