CREATE DATABASE COLLEGE1;
SELECT DATABASE();
USE COLLEGE1;

CREATE TABLE COLLEGE1(
COLLEGE_ID INT PRIMARY KEY,
COLLEGE_NAME VARCHAR(100) NOT NULL,
TOTAL_DEPARTMENTS INT NOT NULL);

INSERT INTO COLLEGE1 VALUES(123,'SEC',10);
INSERT INTO COLLEGE1 VALUES(124,'UEC',15);
INSERT INTO COLLEGE1 VALUES(125,'SRC',16);
INSERT INTO COLLEGE1 VALUES(126,'DDA',18);
INSERT INTO COLLEGE1 VALUES(127,'CHR',11);
INSERT INTO COLLEGE1 VALUES(128,'SBJ',17);
INSERT INTO COLLEGE1 VALUES(129,'SRST',20);
INSERT INTO COLLEGE1 VALUES(113,'SRSR',22);
INSERT INTO COLLEGE1 VALUES(114,'JSS',25);
INSERT INTO COLLEGE1 VALUES(115,'SLC',27);

 SELECT * FROM COLLEGE1;
 
 CREATE TABLE DEPARTMENT_INFO(
DEPARTMENT_NAME VARCHAR(500) PRIMARY KEY,
DEPARTMENT_CODE INT UNIQUE,
STUDENT_USN VARCHAR(500) NOT NULL UNIQUE);

INSERT INTO DEPARTMENT_INFO VALUES('CSE',134,'ISGCSE001');
INSERT INTO DEPARTMENT_INFO VALUES('ISE',234,'ISGISE002');
INSERT INTO DEPARTMENT_INFO VALUES('EEE',334,'ISGEEE003');
INSERT INTO DEPARTMENT_INFO VALUES('EC',434,'ISGEC004');
INSERT INTO DEPARTMENT_INFO VALUES('MECH',534,'ISGME001');
INSERT INTO DEPARTMENT_INFO VALUES('BT',634,'ISGBT001');
INSERT INTO DEPARTMENT_INFO VALUES('CIVIL',734,'ISGCV001');
INSERT INTO DEPARTMENT_INFO VALUES('AMIL',834,'ISGAM001');
INSERT INTO DEPARTMENT_INFO VALUES('DTS',934,'ISGDTS001');
INSERT INTO DEPARTMENT_INFO VALUES('MTS',254,'ISGMTS001');

SELECT * FROM DEPARTMENT_INFO;
SELECT * FROM DEPARTMENT_INFO WHERE DEPARTMENT_NAME='EC';

CREATE TABLE TRAINNER_INFO(
TRAINER_ID INT PRIMARY KEY,
TRAINER_NAME VARCHAR(500) NOT NULL,
TRAINER_ADDRESS VARCHAR(500) UNIQUE);
INSERT INTO TRAINNER_INFO VALUES(12341,'DIVYA','HASSAN');
INSERT INTO TRAINNER_INFO VALUES(12342,'VIDYA','SHIVAMOGGA');
INSERT INTO TRAINNER_INFO VALUES(12343,'LAVANYA','ARSIKERE');
INSERT INTO TRAINNER_INFO VALUES(12344,'RAMYA','BIDHAR');
INSERT INTO TRAINNER_INFO VALUES(12345,'BHAVYA','GULBARGA');
INSERT INTO TRAINNER_INFO VALUES(12346,'KEERTHI','TUMKUR');
INSERT INTO TRAINNER_INFO VALUES(12347,'KARAN','BANGLORE');
INSERT INTO TRAINNER_INFO VALUES(12348,'SHARAN','BEERUR');
INSERT INTO TRAINNER_INFO VALUES(12349,'KAVIN','BAGALKOT');
INSERT INTO TRAINNER_INFO VALUES(123410,'KUSUM','JAVGAL');
 
 SELECT * FROM TRAINNER_INFO;
 
 CREATE TABLE ADMITION_SECTION(
 HR_NAME VARCHAR(500) PRIMARY KEY,
 EXECUTIVE_NAME VARCHAR(500) NOT NULL,
 HR_CONTACT_NUMBER INT UNIQUE);
 
 INSERT INTO ADMITION_SECTION VALUES('SAARA','SUVAS',956745635);
 INSERT INTO ADMITION_SECTION VALUES('DIVYA','SHARAN',956845635);
 INSERT INTO ADMITION_SECTION VALUES('KARUNYA','VIKAS',956645635);
 INSERT INTO ADMITION_SECTION VALUES('SUHAS','SATHWIK',956755635);
 INSERT INTO ADMITION_SECTION VALUES('LAVANYA','CHARAN',956735635);
 INSERT INTO ADMITION_SECTION VALUES('BHUVAN','KUNAL',956785635);
 INSERT INTO ADMITION_SECTION VALUES('HASIB','MAHA',956795635);
 INSERT INTO ADMITION_SECTION VALUES('JAANU','JASHWIN',956765635);
 INSERT INTO ADMITION_SECTION VALUES('KISHAN','JARIN',956725635);
 
 SELECT * FROM ADMITION_SECTION;
 
 CREATE TABLE PLACEMENT_CELL(
 NAME VARCHAR(300) PRIMARY KEY,
 TOTAL_COMPANIES INT NOT NULL,
 HOW_MANY_PLACEMENT INT UNIQUE NOT NULL,
 PAKKAGE VARCHAR(800)NOT NULL);
 
 INSERT INTO PLACEMENT_CELL VALUES('SAARA',20,15,'15LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('DIVYA',25,5,'16LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('KARUNYA',24,12,'17LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('SUHAS',35,120,'20LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('LAVANYA',23,121,'5LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('BHUVAN',22,122,'11LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('HASIB',10,50,'25LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('JAANU',26,34,'35LAKHS');
 INSERT INTO PLACEMENT_CELL VALUES('KISHAN',4,20,'23LAKHS');
 SELECT * FROM PLACEMENT_CELL;
SELECT * FROM PLACEMENT_CELL WHERE PAKKAGE='5LAKHS';

CREATE TABLE EXAM_CELL(
EXAM_CENTER_NAME VARCHAR(400) PRIMARY KEY,
TOTAL_ROOMS INT NOT NULL,
DCS_NAME VARCHAR(600) UNIQUE NOT NULL);

INSERT INTO EXAM_CELL VALUES('SSE',20,'VARUN');
INSERT INTO EXAM_CELL VALUES('SRE',30,'KARAN');
INSERT INTO EXAM_CELL VALUES('SJE',25,'VIRUN');
INSERT INTO EXAM_CELL VALUES('SPE',26,'KAVIN');
INSERT INTO EXAM_CELL VALUES('SSPT',40,'VARIN');
INSERT INTO EXAM_CELL VALUES('JSS',29,'KARUN');
INSERT INTO EXAM_CELL VALUES('SIE',31,'LAVISH');
INSERT INTO EXAM_CELL VALUES('UVC',27,'VAHID');
INSERT INTO EXAM_CELL VALUES('AIR',32,'SHARAN');
INSERT INTO EXAM_CELL VALUES('DDR',33,'KISHVIN');

SELECT * FROM EXAM_CELL;
 
 
 
 